name: CI for Node.js Docker Backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker compose build

      - name: Start services
        run: docker compose up -d --build

      - name: Wait for backend to be healthy
        run: |
          echo "Waiting for backend to be ready..."
          for i in {1..10}; do
            if curl -s http://localhost:8000/health || curl -s http://localhost:8000; then
              echo "Backend is up!"
              exit 0
            fi
            echo "Not ready yet. Retrying in 3s..."
            sleep 3
          done
          echo "Backend failed to start!"
          exit 1

      - name: Shut down services
        if: always()
        run: docker compose down
